name: expense_tracker
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  fpdart: ^1.1.0
  intl: ^0.19.0
  get_it: ^7.7.0
  hive: ^4.0.0-dev.2
  path_provider: ^2.1.3
  isar_flutter_libs: ^4.0.0-dev.13
  flutter_bloc: ^8.1.6
  http: ^1.2.1
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.0
  encrypt: ^5.0.3
  firebase_auth: ^5.1.3
  awesome_dialog: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  package_rename: ^1.6.0



flutter:

  uses-material-design: true


package_rename_config:
  android:
    app_name: Expense Tracker # (String) The display name of the android app
    package_name: com.expensetracker.app # (String) The package name of the android app

  ios:
    app_name: Expense Tracker # (String) The display name of the ios app
    bundle_name: com.expensetracker.app # (String) The bundle name of the ios app
    package_name: com.expense_racker.app # (String) The product bundle identifier of the ios app


  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
